global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment-service:8081']

  - job_name: 'rewards-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['rewards-service:8082']